name: Mirror to GitHub & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ============================================================
  # JOB 1: MIRROR TO GITHUB
  # ============================================================
  mirror_to_github:
    name: Mirror Repository to GitHub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for proper mirroring

      - name: Configure Git
        run: |
          git config --global user.name "Forgejo Mirror Bot"
          git config --global user.email "mirror@forgejo.local"

      - name: Add GitHub Remote
        run: |
          # Remove existing remote if it exists
          git remote remove github 2>/dev/null || true
          
          # Add GitHub remote with authentication
          git remote add github https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }}.git
          
          echo "GitHub remote configured"

      - name: Push to GitHub
        run: |
          # Push all branches
          git push --force github main
          
          # Push all tags (if any)
          git push --force github --tags
          
          echo "Successfully mirrored to GitHub"

  # ============================================================
  # JOB 2: VERIFY RUST BUILDS (Optional Quality Check)
  # ============================================================
  verify_rust:
    name: Verify Rust Backend
    runs-on: ubuntu-latest
    needs: mirror_to_github
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check Rust Code Compiles
        working-directory: backend
        run: cargo check --release
        env:
          SQLX_OFFLINE: true
        continue-on-error: true  # Don't fail the whole pipeline

  # ============================================================
  # JOB 3: TRIGGER RENDER DEPLOYMENTS
  # ============================================================
  deploy_to_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: mirror_to_github
    
    steps:
      - name: Wait for GitHub to Process Push
        run: |
          echo "Waiting 10 seconds for GitHub to process the push..."
          sleep 10

      - name: Trigger Rust Backend Deployment
        run: |
          echo "Triggering Rust backend deployment on Render..."
          echo "Render will pull from GitHub and build the Docker image"
          response=$(curl -X POST -w "\n%{http_code}" -s "${{ secrets.RENDER_DEPLOY_HOOK }}")
          http_code=$(echo "$response" | tail -n1)
          
          if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
            echo "Rust deployment triggered successfully"
          else
            echo "Deployment returned status $http_code"
            echo "$response" | head -n -1
          fi

      - name: Trigger Django Backend Deployment
        run: |
          echo "Triggering Django backend deployment on Render..."
          echo "Render will pull from GitHub and build the Docker image"
          response=$(curl -X POST -w "\n%{http_code}" -s "${{ secrets.RENDER_DJANGO_HOOK }}")
          http_code=$(echo "$response" | tail -n1)
          
          if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
            echo "Django deployment triggered successfully"
          else
            echo "Deployment returned status $http_code"
            echo "$response" | head -n -1
          fi

      - name: Deployment Summary
        run: |
          echo "## Deployment Pipeline Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Steps Completed:" >> $GITHUB_STEP_SUMMARY
          echo "1. Code mirrored to GitHub" >> $GITHUB_STEP_SUMMARY
          echo "2. Rust backend deployment triggered" >> $GITHUB_STEP_SUMMARY
          echo "3. Django backend deployment triggered" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Process:" >> $GITHUB_STEP_SUMMARY
          echo "- Render pulls code from GitHub mirror" >> $GITHUB_STEP_SUMMARY
          echo "- Builds Docker images using Dockerfiles" >> $GITHUB_STEP_SUMMARY
          echo "- Deploys new containers" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Commit Info" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Author:** @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Check Status:**" >> $GITHUB_STEP_SUMMARY
          echo "- [Render Dashboard](https://dashboard.render.com)" >> $GITHUB_STEP_SUMMARY
          echo "- [GitHub Mirror](https://github.com/${{ secrets.GH_REPO }})" >> $GITHUB_STEP_SUMMARY

