// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * --- Dashboard & Profile Schemas (Output) ---
 * AdminDashboardStats
 *
 * Output schema for the administrative statistics dashboard (GET /admin/stats).
 */
export type AdminDashboardStats = { total_projects: bigint, total_users: bigint, total_likes: bigint, 
/**
 * The number of projects where `is_public` is false.
 */
pending_reviews: bigint, };
