// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comment
 *
 * Represents a comment record from the `public.project_comments` table, augmented with
 * the author's email (a join operation).
 */
export type Comment = { id: bigint, user_id: string, project_id: string, comment: string, created_at: string, author_email: string | null, };
