// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CreateCommentRequest
 *
 * Input payload for posting a new comment.
 */
export type CreateCommentRequest = { text: string, };
