// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * --- Request Payloads (Input Schemas) ---
 * CreateProjectRequest
 *
 * Input payload for submitting a new project (POST /projects).
 * The S3 keys are provided here after the client completes the direct-to-cloud upload.
 */
export type CreateProjectRequest = { title: string, abstract_text: string, author_name: string, year: number, cover_image_key: string, video_key: string | null, report_key: string | null, };
