// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Like
 *
 * Internal structure representing a single vote record in the `public.project_likes` table.
 * It is only used internally by the repository for insertion and validation checks.
 */
export type Like = { user_id: string, project_id: string, };
