// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NotificationResponse
 *
 * Enriched response structure for the Frontend (UI Ready).
 * This is the result of joining the internal `Notification` row with user and project details.
 */
export type NotificationResponse = { id: string, actor_email: string, project_id: string, project_title: string, type: string, is_read: boolean, created_at: string, };
