// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PresignedUrlRequest
 *
 * Input payload for requesting a short-lived S3 upload URL (POST /upload/presigned).
 * The server uses these fields to set security constraints on the generated URL.
 */
export type PresignedUrlRequest = { 
/**
 * The original filename, used to derive the file extension.
 */
filename: string, 
/**
 * The MIME type, used to constrain the S3 upload to the allowed type (security).
 */
file_type: string, };
