// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PresignedUrlResponse
 *
 * Output schema containing the secure, temporary URL for client-to-cloud file transfer.
 */
export type PresignedUrlResponse = { 
/**
 * The time-limited URL for the PUT request.
 */
upload_url: string, 
/**
 * The S3 object key where the file will be stored (used to reference the file in the database).
 */
resource_key: string, };
