// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project
 *
 * Represents a final year project record from the `public.projects` table.
 * This is the primary data structure for the core business logic.
 */
export type Project = { id: string, user_id: string, author: string, title: string, 
/**
 * Maps SQL column "abstract" to Rust field "abstract_text".
 * This renaming is necessary because `abstract` is a reserved keyword in Rust.
 */
abstract_text: string, cover_image: string, video: string | null, report: string | null, is_public: boolean, report_is_public: boolean, year: number, created_at: string, updated_at: string, };
