// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RegisterUserRequest
 *
 * Input payload for the public registration endpoint (POST /register).
 * Note: The password is only passed through to the external Auth provider (Supabase) and never
 * persisted or logged internally by this application.
 */
export type RegisterUserRequest = { email: string, password: string, role: string, };
