// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UpdateProjectRequest
 *
 * Partial update payload for modifying an existing project (PUT /projects/{id}).
 *
 * *Optimization*: Uses `Option<T>` for all fields and `#[serde(skip_serializing_if = "Option::is_none")]`
 * to efficiently handle partial updates, ensuring only provided fields are included in the JSON payload.
 */
export type UpdateProjectRequest = { title: string | null, abstract_text: string | null, cover_image_key: string | null, video_key: string | null, report_key: string | null, };
