// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User
 *
 * Represents the user's canonical identity record stored in the `public.profiles` table.
 * This structure includes the minimal required data resolved during authentication.
 */
export type User = { id: string, email: string, role: string, };
