// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UserProfile
 *
 * Output schema for the authenticated user's profile (GET /me).
 * Provides a slightly richer set of data than the internal `User` struct.
 */
export type UserProfile = { id: string, email: string, role: string, avatar_url: string | null, };
