// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a "Like" or "Upvote" on a specific project.
 *
 * This struct corresponds to the join table `votes` in the database.
 */
export type Vote = { 
/**
 * The ID of the user casting the vote.
 */
user_id: string, 
/**
 * The ID of the project receiving the vote.
 */
project_id: string, };
